### PR TITLE
Redo 'PrjSolutionFileWriter'

### PR DESCRIPTION
**Pull request by lewisakura**
Redo 'PrjSolutionFileWriter' to use arguments instead of variables out of a different class. Please reference line 11. You will need to redo how it writes the file.

### CODE REVIEW

**Comment by ByteCrafter** [comment]
Okay, i will test it. I wanted anyways to change it like you did.

**Comment by lewisakura** [comment]
Also, it's good practice to use arguments instead of dragging them out of another class.

**Comment by ByteCrafter** [comment]
Yeah, will merge pull request.

**Comment by lewisakura** [comment]
Thank you.

**Comment by ByteCrafter** [comment]
PS: Why did you forked the Repo? (Just an question :D)

**Comment by lewisakura** [comment]
That's how pull requests work. When you want to commit, you fork it and then submit a pull request. A contributor will then pull it and the commiter can delete the fork.

**Comment by ByteCrafter** [comment]
Ahh, okay.

**Comment by lewisakura** [comment]
All done. Thank you for pulling.

**Comment by ByteCrafter** [comment]
Okay. And no problem! :)

**Comment by lewisakura** [comment]
:)

**Pull request merged**
